### ISSUE TITLE
Impossible to execute commands with arguments

### ISSUE THREAD

**Issue by OrientST** [marcelrv/XiaomiRobotVacuumProtocol#10]
It is impossible to execute any commands that contain arguments. It does not matter how arguments are submitted – with message.payload or in the node settings

All other commands are executed well.

My configuration :
node-red ver.0.18.4
node-red node: node-red-contrib-xiaomi-roborock 0.0.1
roborock  commands: https://github.com/marcelrv/XiaomiRobotVacuumProtocol
roborock  fw_ver: "3.3.9_001518"
roborock  model: "roborock.vacuum.s5"

Could you please explain how to configure commands with arguments.

![node setting](https://user-images.githubusercontent.com/37365091/43678111-ebb87aee-9815-11e8-834c-615e7c325e15.jpg)
![payload](https://user-images.githubusercontent.com/37365091/43678112-ebd3701a-9815-11e8-8080-d66a1429d1ef.jpg)

**Comment by marcelrv** [comment]
Suggest to check this with the writer of node-red-contrib-xiaomi-roborock 0.0.1
