### ISSUE TITLE
Resume zoned cleanup

### ISSUE THREAD

**Issue by Gronis** [marcelrv/XiaomiRobotVacuumProtocol#12]
Hi,

What command should I pass to resume a zoned cleanup? 
Thanks for reverse engineering xiaomi vacuum protocol!

**Comment by alfredkrohmer** [comment]
You just need to send the command for starting spot cleaning again. At least it works this way from the OpenHAB addon.

**Comment by Gronis** [comment]
Not spot cleaning, zoned cleaning, when the vacuum cleans a specified area of the map, specified by coordinates.

**Comment by Markkuuss** [comment]
The command is: `resume_zoned_clean`
