### ISSUE TITLE
Start Selective Room Cleaning

### ISSUE THREAD

**Issue by Markkuuss** [marcelrv/XiaomiRobotVacuumProtocol#23]
Roborock S6 and S5 Max and perhaps other models have the selective room cleaning.

Which command can I use to start cleaning a specific room?

The command app_zoned_clean is only for a square zone. Is there a command e.g. like this?

For example:
```
{
  "id": 8338,
  "method": "app_room_clean", // ????
  "params":[
    "Kitchen", // Room name, as they were named in the app
    "Living room" // further rooms
  ]
}
```

**Comment by Markkuuss** [comment]
Okay, I think I just found the solution here:
https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/1156

The method is called "app_segment_clean".

**Comment by danielkihlgren** [comment]
It should be added so maybe reopen this.

**Comment by Markkuuss** [comment]
I've created PR #25 that includes this.
