### ISSUE TITLE
add basic support for viomi vacuum v7

### ISSUE THREAD

**Issue by merccooper** [marcelrv/XiaomiRobotVacuumProtocol#28]
I've been texting several times in the openhab community but i was ignored.
I got the basic commands for the Viomi vacuum v7. It would be nice to have them in openhab to test them out
`{
	"deviceMapping": {
		"id": [
			"viomi.vacuum.v7"
		],
		"channels": [
			{
				"property": "battary_life",
				"friendlyName": "Battery Level",
				"channel": "battery",
				"type": "Number",
				"refresh": true,
				"ChannelGroup": "Status",
				"actions": []
			},
			{
				"property": "run_state",
				"friendlyName": "Vacuum State",
				"channel": "state",
				"type": "Number",
				"refresh": true,
				"ChannelGroup": "Status",
				"actions": []
			},
			{
				"property": "box_type",
				"friendlyName": "Vacuum Status",
				"channel": "boxtype",
				"type": "Number",
				"refresh": true,
				"ChannelGroup": "Status",
				"actions": []
			},
			{
				"property": "mop_type",
				"friendlyName": "Vacuum Mop Type",
				"channel": "moptype",
				"type": "Number",
				"refresh": true,
				"ChannelGroup": "Status",
				"actions": [
					{
						"command": "set_mop",
						"parameterType": "NUMBER"
					}
				]
			},
			{
				"property": "suction_grade",
				"friendlyName": "Vacuum Power",
				"channel": "suctiongrade",
				"type": "Number",
				"refresh": true,
				"ChannelGroup": "Status",
				"actions": [
					{
						"command": "set_suction",
						"parameterType": "NUMBER"
					}
				]
			},
			{
				"property": "water_grade",
				"friendlyName": "Vacuum Mop Type",
				"channel": "watergrade",
				"type": "Number",
				"refresh": true,
				"ChannelGroup": "Status",
				"actions": [
					{
						"command": "set_suction",
						"parameterType": "NUMBER"
					}
				]
			},
			{
				"property": "err_state",
				"friendlyName": "Error State",
				"channel": "errorstate",
				"type": "Number",
				"refresh": true,
				"ChannelGroup": "Status",
				"actions": []
			},
			{
				"property": "is_mop",
				"friendlyName": "Vacuum Type",
				"channel": "ismop",
				"type": "Number",
				"refresh": true,
				"ChannelGroup": "Status",
				"actions": [
					{
						"command": "set_mop",
						"parameterType": "NUMBER"
					}
				]
			},
			{
				"property": "set_charge",
				"friendlyName": "Send to Dock",
				"channel": "setcharge",
				"type": "Switch",
				"refresh": true,
				"ChannelGroup": "Actions",
				"actions": [
					{
						"command": "set_charge",
						"parameterType": "ONOFF"
					}
				]
			},
			{
				"property": "set_language",
				"friendlyName": "Set Language",
				"channel": "setlanguage",
				"type": "Number",
				"refresh": true,
				"ChannelGroup": "Actions",
				"actions": [
					{
						"command": "set_language",
						"parameterType": "NUMBER"
					}
				]
			},
			{
				"property": "set_light",
				"friendlyName": "Set Light",
				"channel": "setlight",
				"type": "Switch",
				"refresh": true,
				"ChannelGroup": "Actions",
				"actions": [
					{
						"command": "set_light",
						"parameterType": "ONOFF"
					}
				]
			},
			{
				"property": "set_mode_withroom",
				"friendlyName": "Set Mode",
				"channel": "setlanguage",
				"type": "String",
				"refresh": true,
				"ChannelGroup": "Actions",
				"actions": [
					{
						"command": "set_mode_withroom",
						"parameterType": "STRING"
					}
				]
			}
		]
	}
}`

**Comment by marcelrv** [comment]
I'm (long) awaiting the inclusion of https://github.com/openhab/openhab-addons/pull/6693 which allows you to add this file locally, test it out and before we submit it for inclusion in OH. 

That way we don't have untested devices reported as supported which would set unrealistic expectations.

In the mean time, suggest to build the binding with your file included to test it out. If you can confirm it works well we can include it

**Comment by merccooper** [comment]
im not sure how to test it as im new to openhab, i just need to upload the file on the  link that you provide below?

**Comment by merccooper** [comment]
I've been trying to find the folder (getUserDataFolder\miio) but there is not such folder, should i create it?

**Comment by marcelrv** [comment]
The version that includes it is not yet approved, hence it is not in the regular opehnab yet. Download it here:

https://drive.google.com/open?id=1c_F0GsLYdG71qzU7mVd0SM17kir3k1g8

# Advanced: adding local database files to support new devices

Things using the basic handler (miio:basic things) are driven by json 'database' files. This instructs the binding which channels to create, which properties and actions are associated with the channels etc.
The User Data Folder/miio (e.g. in Linux `/opt/openhab2/userdata/miio/`) is scanned for database files and will be used for your devices. Note that local database files take preference over build-in ones. Hence if a json file is local and in the database the local file will be used. For format, please check the current database files in Openhab github.
