### ISSUE TITLE
Map -question

### ISSUE THREAD

**Issue by vsgit19** [marcelrv/XiaomiRobotVacuumProtocol#33]

**Comment by vsgit19** [comment]
What type of encryption the map that is being returned from cloud is encrypted ?

**Comment by marcelrv** [comment]
see the [map folder](https://github.com/marcelrv/XiaomiRobotVacuumProtocol/tree/master/RRMapFile) on the map definitions.
The file is not encrypted when you pull it from the cloud. (outside that the url is using https though)

**Comment by vsgit19** [comment]
Are u sure ? The response i get starts with "eF6lk9uyqk"(This is a long string)

**Comment by marcelrv** [comment]
Maybe your missed  `The file is gzipped, hence needs to be unzipped before reading.`

**Comment by vsgit19** [comment]
Do you have an example file to upload for map(gzip file) ?
Yes i saw you said it is gzipped since my string does not starts with magic number "1f 8b"

**Comment by marcelrv** [comment]
You find example  here
https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/RRMapFile/roboroommap%25252F55512646%25252F6.rrmap

**Comment by marcelrv** [comment]
just to check: you download your file from the link you got in the cloud, right?

e.g. sample URL
https://awsde0.fds.api.xiaomi.com/robomap/roboroommap/55512646/8?Expires=1593388044000&GalaxyAccessKeyId=5271733786446&Signature=XjiFJX86cYNtIwuBth+C0PH/I0M=

**Comment by vsgit19** [comment]
Do you an email ?

**Comment by marcelrv** [comment]
Suggest to take a look at the openhab miio binding for more details. It has the functionality to show the vacuum map

**Comment by vsgit19** [comment]
Hi what is see is that the vacuum sends a request to https://sg.api.io.mi.com/app/v2/home/get_interim_file_url to get the maps.
The response contains url to https://awssgp0.fds.api.xiaomi.com/mi-vacuum-1c/{id}/{did}/2?Expires={data}GalaxyAccessKeyId={data}&Signature={data}.
The data returns from this second url contains a long string that looks encrypted

**Comment by vsgit19** [comment]
so i have three questions:
1. To download the map, i need to perform get_map_v1 directly to the robot and then get something like that: "roboroommap%2255512245%2F1". This data i send to the "/getmapfileurl"  API that should return me something like that "https://awsde0.fds.api.xiaomi.com/robomap/roboroommap/55512646/8?Expires=1593388044000&GalaxyAccessKeyId=5271733786446&Signature=XjiFJX86cYNtIwuBth+C0PH/I0M=".
Correct  ?  as well as  the https://awsde0.fds.api.xiaomi.com/robomap/roboroommap/55512646/8 return all map coordinates  or there are many like this ?   
2. Is this process support the Vacuum 1C type  ? 
3. In the openhab " you said this command related to "Vacuum 1C" ->  "MapView | String | map-map-view". What this command do ?

**Comment by marcelrv** [comment]
1. Correct
2. I don't really know. Most reports are for S5 and s6
Probably the fastest way to answer is to install openhab, add miio binding and add your cloud credentials. See if it gives you the map. If not, the c1 is different. You have the answer in 10 min
3. I don't quit understand your question. Is this in the source code?

**Comment by PiotrMachowski** [comment]
Hi @marcelrv

Great job decoding map file!
I have a question about rrmap file schema: is it possible that it uses [protobuf](https://github.com/protocolbuffers/protobuf) to encode data? It seems to be really similar
