### ISSUE TITLE
Q: Consumables - difference between filter_work_time and filter_element_work_time

### ISSUE THREAD

**Issue by boesing** [marcelrv/XiaomiRobotVacuumProtocol#38]
Hey there,

does anyone know what the difference between `filter_work_time` and `filter_element_work_time` is?
What is the `filter element`?

Are there more than one filter? 🤷‍♂️

**Comment by dsbabkov** [comment]
For information:

My S6 has `filter_work_time: 57527` and `filter_element_work_time: 0` in majordomo system

**Comment by dsbabkov** [comment]
Tested with api:
```
{"result":[{"main_brush_work_time":58143,"side_brush_work_time":58143,"filter_work_time":58143,"filter_element_work_time":0,"sensor_dirty_time":58030}],"id":1606517858}
```

**Comment by gjuhasz86** [comment]
I'm fairly sure `filter_element` is the **mop attachment**. I own an S5 Max, and just gave it a try. The `filter_element_work_time` hasn't been increasing for a while and I indeed haven't use the mopping function recently. Now I attached it and did a quick mopping round, and as a result the `filter_element_work_time` has increased.
