### ISSUE TITLE
roborock.vacuum.m1s available features

### ISSUE THREAD

**Issue by beskit** [marcelrv/XiaomiRobotVacuumProtocol#43]
Hi,
I checked functionality of some endpoints for roborock.vacuum.m1s with software version 3.5.4_0948:  
- app_segment_clean;  
- get_room_mapping.

They worked for me. Can you please add m1s to list of available devices? 

I will continue to inform you about the availability of endpoints.  

Thank you so much for your work!

**Comment by marcelrv** [comment]
feel free to send a PR with changes
