### ISSUE TITLE
Unable to change map

### ISSUE THREAD

**Issue by steeveam** [marcelrv/XiaomiRobotVacuumProtocol#51]
Hello, 
I've implemented my custom android app for sending commands to the vacuum Roborock S5 Max.
Many of the commands listed in this protocol are working, but I miss the option to switch map (to get the vacuum know that he has been moved into map 3 instead of 1). I tried also commands like:
```
reset_map
use_new_map
use_old_map
recover_map
get_recover_map
get_recover_maps
```
but I'm getting response "{'result': 'unknown_method', 'id': ...}"
My lab-status is 3
For enabling lab status (setting to 1, not sure if this should solve the issue) I'm getting: Error: {'code': -10005, 'message': 'Invalid parameters'}

Do you have any idea?
Or do you have even other solution to send the vacuum message "use map Nr. 3"?

**Comment by Zweikeks** [comment]
Hi,
the S5 features other commands, for example
get_persist_map
get_persist_map_v1
get_persist_map_v2
As of other comments I found 'save_map' followed by 'get_persist_map_v1 0' or 'get_persist_map_v1 1' worked somehow.

**Comment by rdorys** [comment]
Hi,
@steeveam  this thread might help you
https://community.home-assistant.io/t/xiaomi-vacuum-restore-select-backup-map-multi-floor-support/282345/5

**Comment by steeveam** [comment]
Thank you rdorys, this was exactly I was looking for: _load_multi_map [1]_
