### ISSUE TITLE
Reverse engineering

### ISSUE THREAD

**Issue by sygys** [marcelrv/XiaomiRobotVacuumProtocol#55]
It looks like all commands are reverse engineered. Maybe this can help somehow to get the commands out of the vacuum that are still unknown or unclear.

I came across a page pointed out to me by a dev that made the integration for the mi heater. It seems like Xiaomi has hidden pages on the internet with all info per device. The challenge would be to find the right one for the job...

This page has all the commands for the za1 heater:
https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:heater:0000A01A:zhimi-za1:1

Replacing the last part A:zhimi-za1:1 with A:zhimi-zb1:1

You will get the smart heater zb1's commands

Me as a n00b have managed to successfully turn my heater on and off just using node red commands. Even Timers and stuff can be read. So I guess If you find the page for the vacuums and other devices. You can do everything and even more the Xiaomi app can do

 I guess there is a page like this for every Xiaomi device out there. The challenge would be to get all pages from that website

**Comment by sygys** [comment]
oh sorry I see now this has already been done :)

**Comment by marcelrv** [comment]
yes, the various developers OS home automation projects (e.g. python-miio / openhab / others) have now mostly developed tooling to do this automatically, so no manual effort needed to parse this.
