### ISSUE TITLE
How can i find coordinates to use in "app_goto_target" and "app_zoned_clean"

### ISSUE THREAD

**Issue by eokgnah** [marcelrv/XiaomiRobotVacuumProtocol#56]
Hi,

i use NodeRed and i can trigger a room cleaning and so on.
I would love to use my triggers as well for "app_zoned_clean".
But im unable to guess which coordinates are mine.
Since i dont see "get_map_v1" in the NodeRed pulldown, im a bit clueless how to obtain my coordinates.

I use node-red-contrib-miio-roborock 2.3.2

I tried to Pin-and-Go in the App and hoped to get the position back, but without any luck.

Would use it for physical buttons to trigger small cleaning jobs.

At least one coordinate would be usefull, because the rest i could manage myself with try&error. But since it seems im way off with my guesses, im clueless.

Thanks
Erich

**Comment by marcelrv** [comment]
I need to disappoint you some more than...
Even with getmap you only get a hint where to find the must in the cloud. It is not possible with stock firmware to obtain the map directly from the vacuum.

I would say the easiest way would be to use openhab +openhab  offline mapviewer, or something similar from Hass. 

https://community.openhab.org/t/xiaomi-vacuum-map-viewer-to-find-coordinates-for-zone-cleaning/103500

**Comment by marcelrv** [comment]
If you insist, see the map folder in this GitHub on how to decode the map file, so you can estimate the coordinates

**Comment by eokgnah** [comment]
All is working now!
Thanks for the Help.
