### ISSUE TITLE
get current coordinates and send to coordinates

### ISSUE THREAD

**Issue by TheNON75** [marcelrv/XiaomiRobotVacuumProtocol#65]
Hello,

this is not a bug report, more like a query or feature reequest.

sorry if it is my fault, but could not find out how to get the current coordinates of the vac and how to send to specific coordinates.

Is there a way already developed or this would be a feature request?

thanks in advance

**Comment by marcelrv** [comment]
Unfortunately there is no command to get the current coordinates.
To instruct the robot to go a coordinate there is the  [goto_target command](https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/goto_target.md)

The only way currently to get the current coordinates (or more specific the last known coordinates) is by decoding the map file. See the section for [RRMap file](https://github.com/marcelrv/XiaomiRobotVacuumProtocol/tree/master/RRMapFile)

note: this repository is only for documenting the commands for the robots. It is no way affiliated with Xiaomi, RoboRock. Hence it is not possible to influence commands they program to their devices.

**Comment by TheNON75** [comment]
thanks @marcelrv ,

i will try that way :)

the note part was clear, just assumed the robot reports it's position within the app, perhaps not implemented yet "here"

thanks for the quick answer
