### ISSUE TITLE
S6 MaxV - get_room_mapping empty

### ISSUE THREAD

**Issue by lacrimal** [marcelrv/XiaomiRobotVacuumProtocol#76]
Hi,

Is room mapping supported for S6 MaxV ?
Getting empty array.
My fw_ver: "3.5.8_6246".

**Comment by dirkhe** [comment]
What did your modelname said?
roborock.vacuum.a????
Do you have special digits in your roomname in app, like üöä.. PLease rename ist, we had the case on S7 Max, which provide empty arrays. It sound it makes no sense, because roomnames are not provided, but sometimes it helps, why ever

**Comment by lacrimal** [comment]
It is roborock.vacuum.a10

And it was almost as you said, names was not present at all, added some names and now getting room id with their numeric identifier.
Thought that will be name but - as I understand - this is MI API so it convert names to unique ID but it is just fine - i will empirically try to figure out which ID is mapped to which room :-)

Thanks
