### ISSUE TITLE
Unable to get info using vacuum.send_command

### ISSUE THREAD

**Issue by mikolajburkiewicz** [marcelrv/XiaomiRobotVacuumProtocol#81]
Hello I am trying to get some info from my Roborock with Node-Red. 

I used call service node and debug node to get the return information. 

When I try f. ex 

{
    "command": "get_status",
    "params": "battery"
}

or any other command which should return information I only get back payload with random string of numbers.

**Comment by marcelrv** [comment]
be aware that the communication is encrypted. 
Likewise, your json is not not correct as get-status doesnot have a parameter (see the page for the command) also your command does not have the sequencial id.

dunno what the node-red is doing exactly in this scenario, but the command to send is:

```
{
    "method": "get_status",
    "id": 96
}
```

**Comment by mikolajburkiewicz** [comment]
I am using node red to trigger different commands. If I want robot to do something f.ex.
{
"command": "find_me"
}

I get voice response from the robot but I can never get any information using get-type commands

**Comment by marcelrv** [comment]
the node-red node you use must be modifying the json that is actually send.
Would suggest to see if it has some debugging feature that allows to see what is actually the command send and the response received.

Alternatively first try your command with python-miio (as raw command) to ensure it works with your robot than 'translate it' to what your node-red node requires

**Comment by mikolajburkiewicz** [comment]
Hmmm. Maybe it is a case of output encoding because I get a response but its not in any readable form like object or array. Just random numbers.
