### ISSUE TITLE
S5 max - distance_off not worked as in docu described

### ISSUE THREAD

**Issue by dirkhe** [marcelrv/XiaomiRobotVacuumProtocol#82]
Hi, I have a s5max and get your docu for distance_off. https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/water_box_custom_mode.md

For the S5max you can't set the level with 
`method": "set_water_box_custom_mode", "params": {"water_box_mode": 207, "distance_off": 60},`
the mode will set, but the level (distance_off) not.

I checked the network traffix and found out, that is done by 
` 'method': 'set_water_box_distance_off', 'params': {'distance_off': 105}}`

The calculation works as expected.

So perhaps you wan't to adapt this to your docu?

**Comment by marcelrv** [comment]
closed via 63a56d9
